-- Gerado por scripts/gerar-migracao.js a partir de src/lib/esquema.js.
CREATE OR REPLACE FUNCTION agora(intervalo interval DEFAULT '0 seconds') RETURNS text
  LANGUAGE sql STABLE AS $$ SELECT to_char((now() + intervalo) AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') $$;

CREATE TABLE IF NOT EXISTS utilizadores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin','tecnico','analista','gestor','externo')),
  ativo INTEGER NOT NULL DEFAULT 1,
  pessoa_id INTEGER,
  criado_em TEXT NOT NULL DEFAULT agora()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_utilizadores_email ON utilizadores (lower(email));

CREATE TABLE IF NOT EXISTS sessoes (
  token TEXT PRIMARY KEY,
  utilizador_id INTEGER NOT NULL REFERENCES utilizadores(id) ON DELETE CASCADE,
  expira_em TEXT NOT NULL
);

-- Tabela Pessoas (identificação). Campos de contacto e BI encriptados.
CREATE TABLE IF NOT EXISTS pessoas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  sexo TEXT,
  data_nascimento DATE,
  bi_hash TEXT UNIQUE,
  bi_enc TEXT,
  telefone_enc TEXT,
  email_enc TEXT,
  morada_enc TEXT,
  provincia TEXT,
  municipio TEXT,
  bairro TEXT,
  consentimento INTEGER NOT NULL DEFAULT 0,
  consentimento_em TEXT,
  estado TEXT NOT NULL DEFAULT 'pendente' CHECK (estado IN ('pendente','validado')),
  completo INTEGER NOT NULL DEFAULT 0,
  campos_em_falta TEXT,
  categoria TEXT,
  prioridade INTEGER,
  prioridade_pontos INTEGER,
  criado_por INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  validado_por INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  validado_em TEXT,
  criado_em TEXT NOT NULL DEFAULT agora(),
  atualizado_em TEXT NOT NULL DEFAULT agora()
);
CREATE INDEX IF NOT EXISTS ix_pessoas_prov ON pessoas(provincia, municipio);
CREATE INDEX IF NOT EXISTS ix_pessoas_estado ON pessoas(estado);

-- Tabela Condições (condição pessoal, causa e funcionalidade)
CREATE TABLE IF NOT EXISTS condicoes (
  pessoa_id INTEGER PRIMARY KEY REFERENCES pessoas(id) ON DELETE CASCADE,
  pcd INTEGER DEFAULT 0, cego INTEGER DEFAULT 0, baixa_visao INTEGER DEFAULT 0, idoso INTEGER DEFAULT 0,
  cadeira_rodas INTEGER DEFAULT 0, muletas INTEGER DEFAULT 0, apoio_permanente INTEGER DEFAULT 0,
  apoio_parcial INTEGER DEFAULT 0, mobilidade_reduzida INTEGER DEFAULT 0,
  tipo_deficiencia TEXT, origem TEXT, causa TEXT, causa_outra TEXT, grau TEXT,
  desloca_sozinho INTEGER DEFAULT 0, ajuda_sair_casa INTEGER DEFAULT 0, apoio_transferencias INTEGER DEFAULT 0,
  sobe_escadas INTEGER DEFAULT 0, transporte_publico INTEGER DEFAULT 0, lim_membros_sup INTEGER DEFAULT 0,
  lim_visual INTEGER DEFAULT 0, lim_comunicacao INTEGER DEFAULT 0, tecnologia_assistiva INTEGER DEFAULT 0
);

-- Tabela Socioeconómica
CREATE TABLE IF NOT EXISTS socioeconomica (
  pessoa_id INTEGER PRIMARY KEY REFERENCES pessoas(id) ON DELETE CASCADE,
  nivel_academico TEXT, sabe_ler INTEGER, situacao_profissional TEXT,
  margem_salarial TEXT, fonte_rendimento TEXT, dependentes INTEGER
);

-- Tabela Procura
CREATE TABLE IF NOT EXISTS procura (
  pessoa_id INTEGER PRIMARY KEY REFERENCES pessoas(id) ON DELETE CASCADE,
  cadeira_manual INTEGER DEFAULT 0, cadeira_eletrica INTEGER DEFAULT 0, oculos_inteligentes INTEGER DEFAULT 0,
  adaptacao_automovel INTEGER DEFAULT 0, manutencao INTEGER DEFAULT 0,
  aquisicao_futura INTEGER DEFAULT 0, compra_imediata INTEGER DEFAULT 0, apoio_social INTEGER DEFAULT 0,
  servico_pretendido TEXT
);

-- Histórico de alterações por registo
CREATE TABLE IF NOT EXISTS historico (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id INTEGER NOT NULL REFERENCES pessoas(id) ON DELETE CASCADE,
  utilizador_id INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  acao TEXT NOT NULL,
  alteracoes TEXT,
  criado_em TEXT NOT NULL DEFAULT agora()
);
CREATE INDEX IF NOT EXISTS ix_historico_pessoa ON historico(pessoa_id);

-- Auditoria de acessos
CREATE TABLE IF NOT EXISTS auditoria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  utilizador_id INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  acao TEXT NOT NULL,
  alvo TEXT,
  ip TEXT,
  criado_em TEXT NOT NULL DEFAULT agora()
);

-- Tabela Relatórios
CREATE TABLE IF NOT EXISTS relatorios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data TEXT NOT NULL DEFAULT agora(),
  tipo TEXT NOT NULL,
  filtros TEXT,
  resultados TEXT,
  utilizador_id INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS parametros (chave TEXT PRIMARY KEY, valor TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS contactos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT, email TEXT NOT NULL, organizacao TEXT, mensagem TEXT,
  criado_em TEXT NOT NULL DEFAULT agora()
);

-- Vista consolidada usada por filtros, estatísticas e relatórios.
CREATE OR REPLACE VIEW v_pessoas AS
SELECT p.id, p.nome, p.sexo, to_char(p.data_nascimento, 'YYYY-MM-DD') AS data_nascimento, p.bi_hash, p.bi_enc, p.telefone_enc,
  p.email_enc, p.morada_enc, p.provincia, p.municipio, p.bairro, p.consentimento, p.consentimento_em, p.estado, p.completo,
  p.campos_em_falta, p.categoria, p.prioridade, p.prioridade_pontos, p.criado_por, p.validado_por, p.validado_em,
  p.criado_em, p.atualizado_em,
  date_part('year', age(p.data_nascimento))::int AS idade,
  c.pcd, c.cego, c.baixa_visao, c.idoso, c.cadeira_rodas, c.muletas, c.apoio_permanente, c.apoio_parcial,
  c.mobilidade_reduzida, c.tipo_deficiencia, c.origem, c.causa, c.causa_outra, c.grau,
  c.desloca_sozinho, c.ajuda_sair_casa, c.apoio_transferencias, c.sobe_escadas, c.transporte_publico,
  c.lim_membros_sup, c.lim_visual, c.lim_comunicacao, c.tecnologia_assistiva,
  s.nivel_academico, s.sabe_ler, s.situacao_profissional, s.margem_salarial, s.fonte_rendimento, s.dependentes,
  r.cadeira_manual, r.cadeira_eletrica, r.oculos_inteligentes, r.adaptacao_automovel, r.manutencao,
  r.aquisicao_futura, r.compra_imediata, r.apoio_social, r.servico_pretendido
FROM pessoas p
LEFT JOIN condicoes c ON c.pessoa_id = p.id
LEFT JOIN socioeconomica s ON s.pessoa_id = p.id
LEFT JOIN procura r ON r.pessoa_id = p.id;
